### ISSUE TITLE
大佬，窝试了试不行啊

### ISSUE THREAD

**Issue by shuzhizhi** [status-code-404/BingGPT_Repost#1]
大佬，窝试了试不行啊
他报{"response_code":"0","response_text":"Something wrong where try to access https://www.bing.com/turing/conversation/create"}

或者{"response_code":"13","response_text":""}

**Comment by status-code-404** [comment]
code 0 是访问 网址的代码不是200，你看看你的环境能否正常访问https://www.bing.com/turing/conversation/create 需要翻墙才能访问 13是发生了我没catch的异常，结合你的这一步的使用来看推测是开了vpn导致requests包找不到host导致了Exception, 你在对应看一下能不能debug

**Comment by status-code-404** [comment]
code 0 是访问 网址的代码不是200，你看看你的环境能否正常访问https://www.bing.com/turing/conversation/create 需要翻墙才能访问 13是发生了我没catch的异常，结合你的这一步的使用来看推测是开了vpn导致requests包找不到host导致了Exception, 你在对应看一下能不能debug

**Comment by status-code-404** [comment]
> 大佬，窝试了试不行啊 他报{"response_code":"0","response_text":"Something wrong where try to access [https://www.bing.com/turing/conversation/create"}](https://www.bing.com/turing/conversation/create%22%7D)
> 
> 或者{"response_code":"13","response_text":""}

code 0 是访问 网址的响应码不是200，你看看你的环境能否正常访问https://www.bing.com/turing/conversation/create 需要翻墙才能访问 13是发生了我没catch的异常，结合你的这一步的使用来看推测是开了vpn全局代理可能导致requests包发生checkhost出现ValueError: check_hostname requires server_hostname导致了Exception, 你在对应看一下能不能debug

**Comment by shuzhizhi** [comment]
code 0 代码 窝在程序 create_conversation.py，第58处打了个断点，得到消息如下
'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">\r\n<HTML><HEAD><TITLE>Bad Request</TITLE>\r\n<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>\r\n<BODY><h2>Bad Request - Invalid Header</h2>\r\n<hr><p>HTTP Error 400. The request has an invalid header name.</p>\r\n</BODY></HTML>\r\n'
但是窝网页单独链接[https://www.bing.com/turing/conversation/create]是没有问题的

**Comment by shuzhizhi** [comment]
![U%9JJ}WT(ARFDB VC57TVVG](https://user-images.githubusercontent.com/81603713/222161857-a26d2094-3be0-4aab-9c71-4cf82c3e82e6.png)

**Comment by status-code-404** [comment]
> [https://www.bing.com/turing/conversation/create
我在自己的服务上尚未遇到这种问题，如果你自己访问https://www.bing.com/turing/conversation/create网址是没有问题的话，可以尝试从浏览器上打开f12 查看网络抓取请求头，**将自己能正常访问的请求头覆盖到template.py的CONVERSATION_HEADER中重试下**

**Comment by status-code-404** [comment]
> code 0 代码 窝在程序 create_conversation.py，第58处打了个断点，得到消息如下 '\r\n<TITLE>Bad Request</TITLE>\r\n\r\n
> ## Bad Request - Invalid Header
> \r\n
> 
> HTTP Error 400. The request has an invalid header name.
> \r\n\r\n'
> 但是窝网页单独链接[https://www.bing.com/turing/conversation/create]是没有问题的

我在自己的服务上尚未遇到这种问题，如果你自己访问https://www.bing.com/turing/conversation/create 网址是没有问题的话，可以尝试从浏览器上打开f12 查看网络抓取请求头，**将自己能正常访问的请求头覆盖到template.py的CONVERSATION_HEADER中重试下**

**Comment by status-code-404** [comment]
你的问题是否得到解决？如果解决了我就将这个issue关掉啦 @shuzhizhi
